package Acme::CPANLists::Import::PerlAdvent::2011_12_04;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2011/2011-12-04.html] (retrieved on 2016-11-06). Visit the URL for the full contents.",entries=>[{module=>"Carp"},{module=>"Carp::Always"},{module=>"Carp::Always::Color"}],summary=>"Modules mentioned in Perl Advent Calendar 2011 (day 04)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2011 (day 04)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2011/2011-12-04.html> (retrieved on 2016-11-06). Visit the URL for the full contents.

