package Acme::CPANLists::Import::PerlAdvent::2011_12_24;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2011/2011-12-24.html] (retrieved on 2016-11-06). Visit the URL for the full contents.",entries=>[{module=>"App::Uni"},{module=>"Unicode::Tussle"}],summary=>"Modules mentioned in Perl Advent Calendar 2011 (day 24)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2011 (day 24)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2011/2011-12-24.html> (retrieved on 2016-11-06). Visit the URL for the full contents.

