package Acme::CPANLists::Import::PerlAdvent::2011_12_21;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2011/2011-12-21.html] (retrieved on 2016-11-06). Visit the URL for the full contents.",entries=>[{module=>"DBD::SQLite"},{module=>"Encode"},{module=>"Encode::DoubleEncodedUTF8"},{module=>"Unicode::Tussle"},{module=>"perl5i"},{module=>"utf8"},{module=>"utf8::all"}],summary=>"Modules mentioned in Perl Advent Calendar 2011 (day 21)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2011 (day 21)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2011/2011-12-21.html> (retrieved on 2016-11-06). Visit the URL for the full contents.

