package Acme::CPANLists::Import::PerlAdvent::2011_12_09;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2011/2011-12-09.html] (retrieved on 2016-11-06). Visit the URL for the full contents.",entries=>[{module=>"Data::Page"},{module=>"Data::Pageset"},{module=>"Data::Paginator"},{module=>"Data::SearchEngine"},{module=>"Data::SearchEngine::ElasticSearch"},{module=>"Data::SearchEngine::Item"},{module=>"Data::SearchEngine::Query"},{module=>"Data::SearchEngine::Results"},{module=>"Data::SearchEngine::Results::Faceted"},{module=>"Data::SearchEngine::Results::Spellcheck"},{module=>"Data::SearchEngine::Solr"},{module=>"MooseX::Storage"},{module=>"MooseX::Storage::Deferred"},{module=>"re"}],summary=>"Modules mentioned in Perl Advent Calendar 2011 (day 09)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2011 (day 09)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2011/2011-12-09.html> (retrieved on 2016-11-06). Visit the URL for the full contents.

